accent = "#9d8ef0"
cursor = "#d6d0f0"
foreground = "#d6d0f0"
background = "#1a1830"
selection_foreground = "#e8e4fa"
selection_background = "#302c50"

color0 = "#262340"
color1 = "#f27a90"
color2 = "#8fd0a8"
color3 = "#f0c888"
color4 = "#6fa8f0"
color5 = "#9d8ef0"
color6 = "#7fe0e0"
color7 = "#c0bce0"
color8 = "#4a4670"
color9 = "#ff92a6"
color10 = "#a6e0bc"
color11 = "#ffd89c"
color12 = "#8fbcff"
color13 = "#b3a6ff"
color14 = "#9cf0f0"
color15 = "#e8e4fa"
